// src/lib/sections/MajorProjects.svelte
<script lang="ts">
  import ResearchProjectEntry from "../components/ResearchProjectEntry.svelte";

  /** define section coordinates */
  const top = -500 * 3;
  const left = (380 - 1500) * 3;
  const top_css = `${top}px`;
  const left_css = `${left}px`;
  const max_width =
    window.innerWidth ||
    document.documentElement.clientWidth ||
    document.body.clientWidth;
  const max_height =
    window.innerHeight ||
    document.documentElement.clientHeight ||
    document.body.clientHeight;

  const activators = [
    {
      header: "start_to_project",
      label: "Projects",
      src: {
        x: 400,
        y: 300,
        width: 100,
        height: 50,
      },
      dst: {
        x: left,
        y: top + 300,
        width: 0,
        height: 0,
      },
      turning_point: {
        x: 400,
        y: top,
      },
    },
    // dst
    {
      header: "projects_to_start",
      label: "Back to start",
      src: {
        x: left + 50,
        y: top,
        width: 100,
        height: 20,
      },
      dst: {
        x: 400,
        y: 0,
        width: 0,
        height: 0,
      },
      // turning_point: {
      //     x: 1000,
      //     y: top,
      // }
    },
  ];
</script>

<!-- Major Projects -->
<div id="projects" class="section projects px-0.5 py-1 gap-y-2">
  <h2 class="section-header">Publications</h2>
  <div class="flex flex-col gap-y-2">
    <ResearchProjectEntry
      teaser_path="awesum.png"
      title="Towards Dataset-scale and Feature-oriented Evaluation of Text Summarization in Large Language Model Prompts"
      authors={[
        "Sam Yu-Te Lee",
        "Aryaman Bahukhandi",
        "Dongyu Liu",
        "Kwan-Liu Ma",
      ]}
      publication="IEEE VIS, 2024, to appear"
      links={[
        ["PDF", "https://ieeexplore.ieee.org/document/10669798"],
        ["Code", "https://github.com/SamLee-dedeboy/Awesum"],
      ]}
    />

    <!-- Research Projects -->
    <ResearchProjectEntry
      teaser_path="hints.jpg"
      title="HINTs: Sensemaking on large collections of documents with Hypergraph visualization and Intelligent agents"
      authors={["Sam Yu-Te Lee", "Kwan-Liu Ma"]}
      publication="TVCG, to appear"
      links={[
        ["PDF", "https://arxiv.org/abs/2403.02752"],
        ["Code", "https://github.com/SamLee-dedeboy/HINTs"],
      ]}
    />
    <ResearchProjectEntry
      teaser_path="nova.png"
      title="NOVA: A visual interface for assessing polarizing media coverage"
      authors={[
        "Keshav Dasu",
        "Sam Yu-Te Lee",
        "Ying-Cheng Chen",
        "Kwan-Liu Ma",
      ]}
      publication="arXiv, 2023"
      links={[
        ["PDF", "https://arxiv.org/abs/2403.00334"],
        ["Code", "https://github.com/SamLee-dedeboy/Nova"],
        ["Demo", "https://samlee-dedeboy.github.io/Nova/"],
      ]}
    />
  </div>
  <!-- Other Projects -->
  <div class="flex flex-col">
    <h2 class="border-b-0">Projects</h2>
    <div class="flex flex-col divide-y">
      <div class="other-project">
        <h3>VisEngineering Guide</h3>
        <div class="text-gray-500">
          Open-Source Documentation of best practices in visualization
          engineering
        </div>
        <div class="links flex">
          <a
            target="”_blank”"
            class="a-button"
            href="https://samlees-organization.gitbook.io/visengineeringguide/"
            >Page</a
          >
        </div>
      </div>

      <div class="other-project">
        <h3>
          Visualizing the career evolution of an individual in the film
          industry.
        </h3>
        <div class="text-gray-500">
          Keywords: Scrollytelling, Automatic story generation
        </div>
        <div class="links flex">
          <a
            target="”_blank”"
            class="a-button"
            href="https://github.com/SamLee-dedeboy/CareerEvolution">Code</a
          >
        </div>
      </div>

      <div class="other-project">
        <h3 class="">
          Evaluating Readability of Graph Layouts with Graph Neural Networks
        </h3>
        <div class="text-gray-500">
          Keywords: Graph Layout, Graph Neural Networks, GAE
        </div>
        <div class="links flex">
          <a
            target="”_blank”"
            class="a-button"
            href="https://github.com/SamLee-dedeboy/graph_layout_GNN">Code</a
          >
        </div>
      </div>
      <div class="other-project">
        <h3 class="">
          Evaluating Empty Space Skipping methods in volume rendering
        </h3>
        <div class="text-gray-500">
          Keywords: Volume Rendering, Empty Space Skipping
        </div>
        <div class="links flex">
          <a
            target="”_blank”"
            class="a-button"
            href="https://github.com/SamLee-dedeboy/AdvancedVisPA">Code</a
          >
        </div>
      </div>
    </div>
  </div>
</div>

<style lang="postcss">
  .projects {
    /* top: v-bind('top_css');
  left: v-bind('left_css'); */
  }
  .other-project {
    @apply px-1 py-2 max-w-[60rem];
    & h3 {
      @apply italic;
    }
  }
  .links {
    @apply mt-1;
  }
</style>

// vue/src/views/components/sections/MajorProjects.vue
<template>
<!-- Major Projects -->
<div id="projects" class='section projects'>
    <h2 class=section-header> Major Projects </h2>
    <!-- first part -->
    <div class=section-content>  
        <div class=slot-header-container>
            <span class=slot-header> Career Evolution Visualization </span>
        </div>
        <ul class=bullets>
            <li class=slot-bullet> Using scrollytelling design to visualize the career evolution of an actor or filmmaker, which can be a director, writer or producer. </li>
            <li class=slot-bullet> Skills used: Scraping and preprocessing (beautifulsoup, python), Front-end Development (Vue.js, HTML/CSS), Interactive Visualization (D3.js), Back-end Development (Flask) </li>
            <li class=slot-bullet> Repo: https://github.com/SamLee-dedeboy/CareerEvolution </li>
        </ul>
    </div>
    <!-- second part -->
    <div class=section-content>  
        <div class=slot-header-container>
            <span class=slot-header> Evaluating Graph Layout Readability with GNN </span>
        </div>
        <ul class=bullets>
            <li class=slot-bullet> Evaluates graph layout readability using GNN, as an alternative to CNNs. </li>
            <li class=slot-bullet> The evaluation is based on reconstruction accuracy of GAEs. </li>
            <li class=slot-bullet> Skills used: Pytorch Geometric (PyG) for building GAEs, python for data processing and analysis. </li>
            <li class=slot-bullet> Repo: https://github.com/SamLee-dedeboy/graph_layout_GNN </li>
        </ul>
    </div>
    <!-- third part -->
    <div class=section-content>  
        <div class=slot-header-container>
            <span class=slot-header> Empty Space Skipping methods evaluation in volume rendering </span>
        </div>
        <ul class=bullets>
            <li class=slot-bullet> Developed a system to support interactive volumetric data visualization and performance testing </li>
            <li class=slot-bullet> Implemented and evaluated three empty space skipping methods: (1) Approximated geometry, (2) Octree-based skipping and (3) SparseLeap, proposed by Hadwiger et al., 2017. </li>
            <li class=slot-bullet> Skills used: WebGL, GLSL </li>
            <li class=slot-bullet> Repo: https://github.com/SamLee-dedeboy/AdvancedVisPA </li>
        </ul>
    </div>
</div>
</template>

<script setup lang=ts>
import * as vue from "vue"
/** define section coordinates */
const top = -500*3
const left = (380 - 1500)*3
const top_css = `${top}px`
const left_css = `${left}px`
const max_width = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
const max_height = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;

const activators = 
[
    {
        header: "start_to_project",
        label: "Projects",
        src: {
            x: 400,
            y: 300,
            width: 100,
            height: 50,
        },
        dst: {
            x: left,
            y: top + 300,
            width: 0,
            height: 0,
        },
        turning_point: {
            x: 400,
            y: top,
        }
    },
    // dst
    {
        header: "projects_to_start",
        label: "Back to start",
        src: {
            x: left + 50,
            y: top,
            width: 100,
            height: 20,
        },
        dst: {
            x: 400,
            y: 0,
            width: 0,
            height: 0,
        },
        // turning_point: {
        //     x: 1000,
        //     y: top,
        // }
    }
]

defineExpose({
    top,
    left,
    activators,
})

</script>

<style scoped>
.projects {
  top: v-bind('top_css');
  left: v-bind('left_css');
}
</style>
